*** Settings ***
Resource    ./abrir_a_pagina_automation_testing_com_diferentes_navegadores_step_definitions.robot
Metadata    Feature    Abrir a pagina automation testing com diferentes navegadores
Metadata    Generated by    _gherkin2robotframework on 2023-09-21T12:37:27.602097_

*** Test Cases ***
Abrir a pagina no navegador "<Browser>" example line 8
    [Template]    Scenario Outline Abrir a pagina no navegador "<Browser>"






*** Keywords ***
Scenario Outline Abrir a pagina no navegador "<Browser>"
    [Documentation]    Dado que eu tenho o navegador "<Browser>"
    ...    Quando eu abro  a pagina automation testing
    ...    Então é exibida a pagina Index
    [Arguments]


